# define global settings here
name: tye-expirement

# define multiple services here
services:
- name: api-one
  project: api-one/api-one.csproj
- name: api-two
  project: api-two/api-two.csproj  
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}"
  tags:
    - redis
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
  tags:
    - redis


  # WHAT ARE TAGS?    
  # - allow for grouping multple services together
  # - start up all the services or a subset of the services e.g tye run --tags=redis

  # executable: app.exe # path to an executable (relative to this file)
  # args: --arg1=3 # arguments to pass to the process
  # replicas: 5 # number of times to launch the application
  # env: # array of environment variables
  #  - name: key
  #    value: value
  # bindings: # optional array of bindings (ports, connection strings)
    # - port: 8080 # number port of the binding
